Now includes wpcheck and various other suggestions
Added wpcheck to evaluate broken plugins or themes thanks to https://github.com/voldemortensen/wcslc-2015/raw/master/troubleshoot.pl

For plugin lists preventing themes and plugins from loading to improve reliability while fetching the list of active plugins.

Checksums verification now in wpstats

diff --git a/qwpcli b/qwpcli
--- a/qwpcli
+++ b/qwpcli
@@ -3,7 +3,7 @@
 ###############################
 #                             #
 # Developed by: Rowdy Adams   #
-# Updated on:   25 May 2016   #
+# Updated on:   08 Jun 2016   #
 #                             # 
 ###############################
 
@@ -14,12 +14,10 @@ for cmd in `echo $PATH|sed "s/:/ /g"|xargs ls 2>/dev/null|grep -v '/'`;do alias 
 alias ls='/bin/ls --color=tty -F -A -b -T 0'
 ###
 
-#echo "alias wp='/usr/php/54/usr/bin/php-cli /usr/php/54/usr/bin/wp'" >> ~/.bashrc && source ~/.bashrc
-
-#alias wp='/usr/php/54/usr/bin/php-cli /usr/php/54/usr/bin/wp'
 alias wp='/usr/php/54/usr/bin/php-cli /usr/local/bin/wp'
 
-#DIRS=$(find ~/public_html -maxdepth 5 -type f -name 'wp-config.php')
+# Required for gcmd commands #
+DIRS=$(find ~/public_html -maxdepth 5 -type f -name 'wp-config.php')
 
 # Colors
 ESC_SEQ="\x1b["
@@ -50,7 +48,7 @@ $COL_GREEN \___\_\_,_/_/\__/_/\_\  $COL_GREEN |__/|__/_/       \___/____/___/  $
 $COL_CHERRY
 What would you like added to QWPCLI? Let me know!$COL_PURPLE http://goo.gl/forms/R2h7aTZXrX$COL_RESET\nType$COL_CYAN qwpcli$COL_RESET to return to this menu:
 
-What would you like to work on?                           $COL_GREEN Updated: 25 May 2016
+What would you like to work on?                           $COL_GREEN Updated: 08 Jun 2016
 
   $COL_CYAN wpstats $COL_RESET  - Show Version, URL, DB Info, Number of Available Updates
   $COL_CYAN wpcore $COL_RESET   - Check Versions, Verify Checksums, Replace Core Files
@@ -70,7 +68,7 @@ CHECK=$(wp core version | wc -l)
 
 if [ $CHECK != '1' ]; then
 echo -e "$COL_MAGENTA 
-WARNING WPCLI CHECK: [FAILED] 
+WARNING WPCLI CHECK: [FAILED]
 $COL_RESET
 WPCLI is having trouble working. Are you in a WordPress directory? If so run:$COL_CYAN wp core version$COL_RESET. If you do not get any results report an error by runing$COL_CYAN qerror$COL_RESET. 
 "
@@ -95,7 +93,7 @@ WordPress Specific:$COL_RESET
   $COL_CYAN dblist $COL_RESET   - Lists Database Names and wp-config.php Locations
   $COL_CYAN wpspeed $COL_RESET  - Runs WordPress Speed Checks
   $COL_CYAN wpopt $COL_RESET    - Basic Site Optimization and Suggestions
-  $COL_CYAN wpinstall $COL_RESET- Install WordPress from scratch 
+  $COL_CYAN wpinstall $COL_RESET- Install WordPress From Scratch 
   $COL_CYAN wptools $COL_RESET  - Show WordPress Tools Functions $COL_GREEN
 Helpful Functions:$COL_RESET
   $COL_CYAN fcount $COL_RESET   - Lists Number of Files in Current Directory
@@ -138,7 +136,7 @@ What global actions would you like to take?
 (9) Overhall (Replace Core, Flush Permalinks, Flush Cache, Media Regenerate, Opt & Repair DB)
 (0) Exit
 $COL_MAGENTA
-Want to run another command? use$COL_CYAN gcmd [COMMAND]$COL_MAGENTA to run any comamnd in all WordPress directories!
+Want to run another command? use$COL_CYAN gcmd [COMMAND]$COL_MAGENTA to run any command in all WordPress directories!
 $COL_RESET
 \tSelection: \c" ;
 read globalSelect && echo ''
@@ -258,9 +256,9 @@ esac
 }
 ### Plugin Menu ###
 function wpplugin() {
-PLUGNUM=$(wp plugin list | wc -l)
-ACTIVEPLUG=$(wp plugin list | grep -w active | wc -l)
-TOTALPLUG=$(wp plugin list | grep -w -E "inactive|active" | wc -l)
+PLUGNUM=$(wp --skip-plugins --skip-themes plugin list | wc -l)
+ACTIVEPLUG=$(wp --skip-plugins --skip-themes plugin list | grep -w active | wc -l)
+TOTALPLUG=$(wp --skip-plugins --skip-themes plugin list | grep -w -E "inactive|active" | wc -l)
 
 echo -e "$COL_GREEN
 Active Plugins: $ACTIVEPLUG
@@ -398,7 +396,7 @@ function wpstats(){
 ###Get the info from the wp-config file
 read -r dbhost dbname dbpass dbuser dbprefix <<< $(cat wp-config.php | egrep "^[^/].*[\"']DB_(NAME|USER|PASSWORD|HOST[^_])|table_prefix" | sort -d | sed "s/.*[\"']\(.*\)[\"'].*;.*/\1/") 
 
-PLUGIN=$(wp plugin list | grep -w available | wc -l)
+PLUGIN=$(wp --skip-plugins --skip-themes plugin list | grep -w available | wc -l)
 THEME=$(wp theme list | grep -w available | wc -l)
 CORE=$(wp core check-update | grep -w wordpress | wc -l)
 
@@ -410,6 +408,13 @@ if [ $CHECK == '1' ]; then
 	echo -e "$COL_GREEN\rWPCLI Check:$COL_GREEN    [OK] $COL_GREEN"
 else
 	echo -e "$COL_GREEN\rWPCLI Check:$COL_MAGENTA [FAILED]   Report Errors with$COL_CYAN qerror$COL_GREEN"
+fi
+
+HACK=$(wp core verify-checksums 2>&1 | wc -l)
+if [ $HACK == '1' ]; then
+        echo -e "$COL_GREEN\rChecksums:$COL_GREEN      [OK] $COL_GREEN"
+else
+        echo -e "$COL_GREEN\rChecksums:$COL_MAGENTA      [FAILED]   Run Full Report From$COL_CYAN wpcore$COL_MAGENTA Menu $COL_GREEN"
 fi
 
 wp eval --skip-plugins 'echo "Eval Plugins:   [OK]\n";'
@@ -536,7 +541,7 @@ wp transient delete-expired
 
 ### PLUGIN LIST ###
 function wpPluginList(){
-wp plugin list
+wp --skip-plugins --skip-themes plugin list
 }
 ### TOGGLE PLUGINS ###
 function wpPluginToggle(){
@@ -551,7 +556,7 @@ wp plugin toggle $PLUGINS
 function wpPluginDeactivate(){
 ACTIVEPLUG=$(wp plugin deactivate --all >.QWPCLI_ACTIVEPLUGINS.txt 2>&1 && <.QWPCLI_ACTIVEPLUGINS.txt awk '$1=="Success:" {print $3}' | tr -d \')
 # '
-wp plugin list
+wp --skip-plugins --skip-themes plugin list
 }
 ### ACTIVATE PLUGINS ###
 function wpPluginActivate(){
@@ -1370,7 +1375,7 @@ wp option set time_format 'g:i A'
 echo -e "$COL_MAGENTA
 Now disabling comments and pingbacks on existing content... $COL_RESET"
 sleep 1
-wp post update $(wp post list --format=ids) ---comment_status=closed
+wp post update $(wp post list --format=ids) --comment_status=closed
 wp post update $(wp post list --format=ids) --ping_status=closed
 
 echo -e "$COL_GREEN
@@ -1393,7 +1398,7 @@ wp option set posts_per_page 5
 echo -e "$COL_MAGENTA
 Now disabling comments and pingbacks on existing content... $COL_RESET"
 sleep 1
-wp post update $(wp post list --format=ids) ---comment_status=closed
+wp post update $(wp post list --format=ids) --comment_status=closed
 wp post update $(wp post list --format=ids) --ping_status=closed
 
 echo -e "$COL_GREEN
@@ -1693,7 +1698,7 @@ WordPress Tools GUI.$COL_RESET Choose a Function below:
 
 \tSelection: \c" ;
 
-read optSelect && echo ''
+read toolsSelect && echo ''
 case $toolsSelect in
 	1)	wptoolsbackup;; 
 	2)	wptoolsrestore;; 
@@ -1765,6 +1770,19 @@ cd ~
 wp-tools upgrade --path=$WPDIR --backupdir=backupwordpress/$BACKUPDIR --wp-cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"
 cd $DIR
 }
+
+function wpcheck(){
+if [ ! -f troubleshoot.pl ]; then
+wget https://github.com/voldemortensen/wcslc-2015/raw/master/troubleshoot.pl
+echo -e "$COL_GREEN \nLatest troubleshoot.pl downloaded $COL_RESET"
+fi
+
+echo -e "$COL_GREEN \nChecking for Plugin and Theme Issues...\n $COL_RESET"
+perl troubleshoot.pl --all --wp_cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"
+}
+
+clean_up_files () { find ~/public_html/ -maxdepth 5 \( -name "troubleshoot.pl" -o -name "qwpcli*" \)|xargs rm -rf; }
+trap clean_up_files EXIT
 
 #################### END WP-TOOLS FUNCTIONS ####################
 
